export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_DELIVERED_REQUEST = "ORDER_DELIVERED_REQUEST";
export const ORDER_DELIVERED_SUCCESS = "ORDER_DELIVERED_SUCCESS";
export const ORDER_DELIVERED_FAIL = "ORDER_DELIVERED_FAIL";
export const ORDER_DELIVERED_RESET = "ORDER_DELIVERED_RESET";

export const ORDER_PAYMENT_STATUS_UPDATE_REQUEST =
  "ORDER_PAYMENT_STATUS_UPDATE_REQUEST";
export const ORDER_PAYMENT_STATUS_UPDATE_SUCCESS =
  "ORDER_PAYMENT_STATUS_UPDATE_SUCCESS";
export const ORDER_PAYMENT_STATUS_UPDATE_FAIL =
  "ORDER_PAYMENT_STATUS_UPDATE_FAIL";
export const ORDER_PAYMENT_STATUS_UPDATE_RESET =
  "ORDER_PAYMENT_STATUS_UPDATE_RESET";

// export const ORDER_CANCEL_REQUEST = "ORDER_CANCEL_REQUEST";
// export const ORDER_CANCEL_SUCCESS = "ORDER_CANCEL_SUCCESS";
// export const ORDER_CANCEL_FAIL = "ORDER_CANCEL_FAIL";
// export const ORDER_CANCEL_RESET = "ORDER_CANCEL_RESET";

// export const ORDER_RETURN_REQUEST = "ORDER_RETURN_REQUEST";
// export const ORDER_RETURN_SUCCESS = "ORDER_RETURN_SUCCESS";
// export const ORDER_RETURN_FAIL = "ORDER_RETURN_FAIL";
// export const ORDER_RETURN_RESET = "ORDER_RETURN_RESET";

// Constants for Admin approving/rejecting cancellation
export const ORDER_ADMIN_APPROVE_CANCEL_REQUEST =
  "ORDER_ADMIN_APPROVE_CANCEL_REQUEST";
export const ORDER_ADMIN_APPROVE_CANCEL_SUCCESS =
  "ORDER_ADMIN_APPROVE_CANCEL_SUCCESS";
export const ORDER_ADMIN_APPROVE_CANCEL_FAIL =
  "ORDER_ADMIN_APPROVE_CANCEL_FAIL";
export const ORDER_ADMIN_APPROVE_CANCEL_RESET =
  "ORDER_ADMIN_APPROVE_CANCEL_RESET";

export const ORDER_ADMIN_REJECT_CANCEL_REQUEST =
  "ORDER_ADMIN_REJECT_CANCEL_REQUEST";
export const ORDER_ADMIN_REJECT_CANCEL_SUCCESS =
  "ORDER_ADMIN_REJECT_CANCEL_SUCCESS";
export const ORDER_ADMIN_REJECT_CANCEL_FAIL = "ORDER_ADMIN_REJECT_CANCEL_FAIL";
export const ORDER_ADMIN_REJECT_CANCEL_RESET =
  "ORDER_ADMIN_REJECT_CANCEL_RESET";

// Constants for Admin approving/rejecting return
export const ORDER_ADMIN_APPROVE_RETURN_REQUEST =
  "ORDER_ADMIN_APPROVE_RETURN_REQUEST";
export const ORDER_ADMIN_APPROVE_RETURN_SUCCESS =
  "ORDER_ADMIN_APPROVE_RETURN_SUCCESS";
export const ORDER_ADMIN_APPROVE_RETURN_FAIL =
  "ORDER_ADMIN_APPROVE_RETURN_FAIL";
export const ORDER_ADMIN_APPROVE_RETURN_RESET =
  "ORDER_ADMIN_APPROVE_RETURN_RESET";

export const ORDER_ADMIN_REJECT_RETURN_REQUEST =
  "ORDER_ADMIN_REJECT_RETURN_REQUEST";
export const ORDER_ADMIN_REJECT_RETURN_SUCCESS =
  "ORDER_ADMIN_REJECT_RETURN_SUCCESS";
export const ORDER_ADMIN_REJECT_RETURN_FAIL = "ORDER_ADMIN_REJECT_RETURN_FAIL";
export const ORDER_ADMIN_REJECT_RETURN_RESET =
  "ORDER_ADMIN_REJECT_RETURN_RESET";
